### PR TITLE
Open ai api setup

### PR DESCRIPTION
**Pull request by LucileTech**
Screenshot 2024-07-12 at 17 04 45

### CODE REVIEW

**Comment by huyfififi** [comment]
#38 
Also, is it possible to split this pull requests into smaller chunks? such as one for the backend and the other for the frontend.
It's generally a good practice to keep a pull request minimal, so that reviewers can easily understand and review the changes

**Comment by LucileTech** [comment]
> #38 Also, is it possible to split this pull requests into smaller chunks? such as one for the backend and the other for the frontend. It's generally a good practice to keep a pull request minimal, so that reviewers can easily understand and review the changes

Thank you for your review! My .env is ready, thank you for working on a .env PR. I will separate my work into smaller chunks, one Front and one Back

**Comment by huyfififi** [comment]
Thank you so much 🙏  that would be super helpful

**Comment by mie-h** [comment]
Lucile is busy with her interviews this week.

**Pull request closed without merging**
